### ISSUE TITLE
How does this repo fit for projects we don't manage?

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/org-ops#3]
### Summary

As discussed in https://github.com/2i2c-org/team-compass/issues/136, the Pangeo GCP project currently only allows access to columbia.edu emails, and hence we do not have enough permissions to manage that project from this repo as we do with our other projects. This issue will track idea generation and discussion around team processes for such projects in the future and how the org-ops repo fits into that story.

**Comment by yuvipanda** [comment]
This is one of the big reasons we're going to archive this repo, see #4
